### ISSUE TITLE
how to use it with overlay

### ISSUE THREAD

**Issue by ha-family** [jcc/v-textcomplete#2]
hi , can i use it like link below
https://yuku-t.com/jquery-textcomplete/

with jquery overlay???

thx

**Comment by jcc** [comment]
What? You want to import `Jquery` ?

**Comment by ha-family** [comment]
i want to add highlight on the textarea
i think it would be better if i don't have to
but i already use  jquery inside my project (vue + laravel)
do you have any suggestions for me ??

**Comment by ha-family** [comment]
哈囉，您是中國人吧，我打中文應該比較好 :)
想請問您，如果像是mention name
是否在當 @名字 後面加一個空白的時候會有一個callback讓我知道已經取樣了一個名字
即便使用者沒有選擇autocomplete的選項

這樣如果當使用者沒有找到 @名字 的時候，我還可以設計一些前端的效果

還麻煩您給我點意見，因為直接使用別人的vue component我的經驗還不是這麼豐富
希望您不吝給我意見，謝謝

**Comment by jcc** [comment]
@liu-yuhuan 但你想要的是什么样的前端效果，我觉得这个完全没必要，找不到就直接没有效果。因为用户就只是想 @ 某人，你只需要将文章或者是 pr 的有关联的人的名字列出即可。当然这个还是需要看你的需求的。

这是一个 vue 组件，如果你使用 jquery 并没有什么影响的，只是你打包代码的时候，文件会大一些。

**Comment by ha-family** [comment]
我是想用#來標注關鍵字，所以當找不到用過的關鍵字的時候
就新增一個新的關鍵字到textarea底下，加一個tag之類的

**Comment by ha-family** [comment]
不知道strategies底下有沒有function可以偵測 #關鍵字 （關鍵字後面有空白的時候，就callback
我就可以加一個標籤
大概想法是這樣

**Comment by jcc** [comment]
strategies 中你可以写各种策略的。你可以使用正则尝试匹配一下

**Comment by liu-yuhuan** [comment]
好的～謝謝喔

**Comment by ha-family** [comment]
好的～感謝

**Comment by ha-family** [comment]
請問一下有keydown的event嗎？
謝謝

**Comment by jcc** [comment]
@liu-yuhuan 有，但是没有 emit。

**Comment by ha-family** [comment]
可以教我該如何使用嗎？
謝謝

**Comment by jcc** [comment]
@liu-yuhuan 你这里有什么的需求么？如果有，你可以看一看 keyEvent.js 怎么添加，然后提 pr 给我。可以么？

**Comment by ha-family** [comment]
就是我想要擷取tag的時候
會有問題，如果原本已經保存 #AB 但是使用者如果刪除掉B的時候，
我會不知道是新輸入一個 #A 又或是從 #AB（移除掉Ｂ） 所以我想偵測使用者是不是按了delete鍵
去判斷他的輸入

請問該怎麼提pr??
應該是可以對textarea使用
document.getElementById('textarea').addEventListener('keydown', function (e){
    
}, false);

**Comment by jcc** [comment]
我来加吧，我在 keydown 的事件加个 emit

**Comment by ha-family** [comment]
感激不盡！！！
那請問一下我怎麼使用npm更新這個？？

**Comment by jcc** [comment]
用法：
```html
<template>
  <text-complete v-model="content" :strategies="strategies" @key-down="onKeyDown"></text-complete>
</template>

<script>
import TextComplete from 'v-textcomplete'

export default {
  components: { TextComplete },
  data() {
    return {
      show: false,
      content: '',
      strategies: [{
        match: /(^|\s)@([a-z0-9+\-\_]*)$/,
        template(name) {
          return '<span class="m-2">' + name + '</span>'
        },
        search(item, callback) {},
        replace(value) {
          return '$1' + value + ' '
        },
        list: [ '@Jiajian', '@Overtrue', '@Jelly', '@Mike' ],
      }]
    }
  },
  methods: {
    onKeyDown(e) {
      console.log('Key Down : ' + e)
    }
  },
}
</script>
```

**Comment by jcc** [comment]
@liu-yuhuan 更新到 0.2.4 版本即可

**Comment by ha-family** [comment]
感激不盡！！！謝謝

**Comment by ha-family** [comment]
不好意思，請問可以新增keyup的event嗎？
因為key-down的Event在取得textarea的value會少字元
ＱＱ

**Comment by jcc** [comment]
@liu-yuhuan 用法给 keydown 一样

**Comment by ha-family** [comment]
感謝你！！！
