### ISSUE TITLE
是否可以不用正则来匹配？

### ISSUE THREAD

**Issue by youngchen1987** [jcc/v-textcomplete#3]
是否可以不用正则来匹配？
https://yuku-t.com/jquery-textcomplete/ 像老版本这样的？
![image](https://user-images.githubusercontent.com/11566474/35261067-7e828c08-0049-11e8-8b40-c219e5c8e6b8.png)

**Comment by jcc** [comment]
???? 这个 jquery 的版本不就也是用正则匹配的吗？

**Comment by youngchen1987** [comment]
这个中文可以吗？

**Comment by youngchen1987** [comment]
可否留个qq  我想咨询一下问题 看这个组件是否合适？ 因为看这个文档写的比较简单

**Comment by youngchen1987** [comment]
谢谢了
